### ISSUE TITLE
Binary Value Behavior error

### ISSUE THREAD

**Issue by BeneficialCode** [zodiacon/TotalRegistry#32]
_BinaryValueDlg's edit control  （IDC_NAME）can get the mouse focus when WM_LBUTTONDOWN, although it is read only. This will capture the input focus forever when this case occurs. 
Then the hex control will not never get the input focus._

**Comment by BeneficialCode** [comment]
Use your mouse's left button on the edit box, then this will occurs.

**Comment by BeneficialCode** [comment]
![image](https://user-images.githubusercontent.com/40847073/139565059-37c51955-ac67-45d7-be3a-6935ea15d3a7.png)

**Comment by zodiacon** [comment]
Should be fixed now.
