### ISSUE TITLE
Feature Request: Back, Forward, Favorite, History, and more

### ISSUE THREAD

**Issue by David-Maisonave** [zodiacon/TotalRegistry#33]
I've always wanted a back and forward option on RegEdit. Moreover, there are several features on a browser that would be great to have on a RegEdit tool.

1. Back (option on toolbar to go to previous registry address)
2. Forward (toolbar option to move forward to last address before Back option used)
3. Up (toolbar option similar to File Explorer, where address moves to parent address)
3. Favorite or Bookmarks (A Node at the same level as "Standard Registry" and "REGISTRY". The node contains user defined registry key book marks)
4. History or MRU [Most Recently Used] (list with the last [MAXRECENT] 100 visited addresses. Allow user to change the MAXRECENT value)
5. Tabs (Similar TAB GUI seen in Chrome and Firefox)
6. Start up with the last address location in previous session by using the same key used by RegEdit and updating it when session exits. (HKCU\Software\Microsoft\Windows\CurrentVersion\Applets\Regedit\Lastkey)

Additional Feature Request:

- When a registry key value is enter on the address bar, have the parent key selected. Same as what happens when a registry key is entered.
- If a user paste an address starting with "Computer\", automatically remove that string. That will allow users to copy an address in RegEdit, and paste it on RegExp.
- Have a Common (or Popular) node at the same level as "Standard Registry". The Common node can have a list of the most popular keys. Example:
  - CurrentVersion
    - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    - HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion
  - SOFTWARE
    - HKEY_CURRENT_USER\SOFTWARE
    - HKEY_LOCAL_MACHINE\SOFTWARE
  - Run
    - HKLM
      - HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run
      - HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce
    - HKCU
      - HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
      - HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunOnce
  - HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Applets\Regedit
  - HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager

If you need help with some of this, I can create some pull request.

**Comment by zodiacon** [comment]
Very good ideas indeed!
You're welcome to contribute :)

**Comment by David-Maisonave** [comment]
I just uploaded the latest release of RegExp, and I notice this version does remember last session address. However, it's independent of RegEdit last session address. 
Wouldn't it be better if they both used the same registry key for last key?
HKCU\Software\Microsoft\Windows\CurrentVersion\Applets\Regedit\Lastkey

That would make it so users can easily switch back and forth between RegEdit and RegExp, and not have to worry about which one had the last key used.

**Comment by zodiacon** [comment]
Good point.

**Comment by zodiacon** [comment]
Added Back/Forward buttons (you'll have to build the project or download from the AllTools repo)

**Comment by snowman** [comment]
And clickable breadcrumbs would be awesome!

**Comment by David-Maisonave** [comment]
Hi snowman,
I had to look up "clickable breadcrumbs" to figure out what you were referring to, and now that I understand, I think it's a good idea.
But (IMHO) I think it should go on a separate feature request, and have a little more details.

After testing the changes for this request, I'll post your request myself if you don't mine, and I'll include the details.

**Comment by zodiacon** [comment]
Thank you for the detailed feedback!
The tool name change was necessary because it appears there is already a tool called Registry Explorer that I was not aware of :(
