### ISSUE TITLE
If systemwide dark mode for apps is enabled, please default to dark mode in Total Registry as well

### ISSUE THREAD

**Issue by unforgettableid** [zodiacon/TotalRegistry#37]
When I start Total Registry for the first time, please [check if systemwide dark mode for apps has been enabled](https://stackoverflow.com/questions/38734615/how-can-i-detect-windows-10-light-dark-mode) in the Windows Settings app. If it's enabled, please enable Total Registry's dark mode too.

Thank you for reading this, and for all the work you've done on Total Registry!

**Comment by T0m0rr0w** [comment]
Agreed. Would be nice if it could follow the system setting.

**Comment by zodiacon** [comment]
Thank you both. I'm adding this to my backlog.

**Comment by unforgettableid** [comment]
No worries!

Now that my machine automatically switches between dark and light mode at sunrise/sunset, I realize that my original request isn't quite ideal.  Checking for the system dark/light theme state just once, at first run, is perhaps not really ideal.  It might be better if Total Registry could check this more often.

I've created a modified version of my original feature request:  please see #62.

I'm closing this older issue in favor of that newer issue.
