### ISSUE TITLE
BookMarks

### ISSUE THREAD

**Issue by C1ayMa5k** [zodiacon/TotalRegistry#41]
My Bookmarks always gone and can't find them back :(
when reopen it

**Comment by zodiacon** [comment]
Will check!

**Comment by zodiacon** [comment]
It works for me... can you provide more details to repro?

**Comment by C1ayMa5k** [comment]
Sometimes they exist when reopen,sometimes they gone and can't find back.
I can't provide more details because I didn't do anything else.
Really a strange bug...
But thanks for reply!

**Comment by zodiacon** [comment]
Should be fixed now. (grab from AllTools repo)
