### ISSUE TITLE
HyperLink is error address

### ISSUE THREAD

**Issue by BeneficialCode** [zodiacon/TotalRegistry#43]
![image](https://user-images.githubusercontent.com/40847073/172279554-74f7c353-5d11-4ec0-bd3c-3025e72f7c26.png)
404 Not Found.
![image](https://user-images.githubusercontent.com/40847073/172279621-43416ddb-87df-4971-b0d5-fe0da7470507.png)
Not a big deal.

**Comment by zodiacon** [comment]
Thanks, fixed :)
