### ISSUE TITLE
HKEY_USERS registry keys inaccessible, Run as admin error, and HKLM inaccessible.

### ISSUE THREAD

**Issue by David-Maisonave** [zodiacon/TotalRegistry#45]
Version: 0.96
I tried running the program in normal mode, but certain users under the HKEY_USERS keys were inaccessible.
<img width="620" alt="HKEY_USERS_SubusersInaccessible" src="https://user-images.githubusercontent.com/47364845/175829524-a2e06113-3ad5-45ef-b627-117596f5afc6.png">

So I tried running  the program with the "Run as Admin" option, but I got an error message "Failed to Load Kernel Driver".
<img width="292" alt="FailedToLoadKernelDriver" src="https://user-images.githubusercontent.com/47364845/175829222-8ca14b0b-ddbf-4432-a3c3-03d364f4c1f9.png">

After pressing OK, I was able to view the user's registry key.
<img width="620" alt="HKEY_USERS_Accessible" src="https://user-images.githubusercontent.com/47364845/175829836-8650fb74-0bf2-4b69-bbc0-8cb293de3264.png">

When I run RegEdit in normal mode, all the HKEY_USERS keys are accessible.
<img width="622" alt="RegEdit_HKEY_USERS_Accessible" src="https://user-images.githubusercontent.com/47364845/175830160-dc4b6f0c-d46c-4a97-af45-401131337e5b.png">

When using the Powershell registry key format, the key is inaccessible.
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\SessionData
<img width="409" alt="HKLM_inaccessible" src="https://user-images.githubusercontent.com/47364845/175831071-751d25e3-6d4d-41db-90fa-cb3a1d8c708c.png">

If I enter it with the standard format it works.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\SessionData

1. Can the error message be removed?
2. Is there a way to have the program work more like RegEdit, where running in admin mode is not required for accessing these keys?
3. Can the Powershell format be fixed?  Maybe just have it automatically convert what's pasted to the standard format.

FYI:
Thank you for adding the Book Mark feature!
I'm testing a script that runs as another user, and it changes registries at user level and HKEY_LOCAL_MACHINE.  With the book marks, it's so easy to move around.

**Comment by zodiacon** [comment]
I will remove the error message as I have disabled the driver for now.
If you're an admin on your machine, RegEdit requires you to elevate, which is why you have access to those keys.
I will add support for the Powershell format (good point).
Thanks for the feedback!

**Comment by David-Maisonave** [comment]
> If you're an admin on your machine, RegEdit requires you to elevate, which is why you have access to those keys.

I have Windows 11 Pro on my desktop computer.  When I start RegEdit, I don't get an elevated prompt, but RegEdit still has access to all the users under HKEY_USERS.

On my Windows 11 laptop, when RegEdit starts, I get the following prompt:
![Win11_RegEditStartUpPrompt smaller](https://user-images.githubusercontent.com/47364845/176956974-a2af7bba-ea9e-4781-a243-f4f956f5cbec.png)

In either case I have access to all the users under HKEY_USERS.  It seems RegEdit automatically elevates without prompting the user.  I'm not sure how RegEdit does that, but it would be more consistent if TotalRegistry could behaves similar.

**Comment by zodiacon** [comment]
RegEdit uses the manifest entry called "highestAvailable" to ask for elevation if the user is a true admin.
My goal is not to mimic Regedit. I think this Regedit behavior is not good, because it forces you to run it elevated, even if you don't want to.
