### ISSUE TITLE
Find controls are invisible until interaction on Windows 7

### ISSUE THREAD

**Issue by Mingun** [zodiacon/TotalRegistry#55]
This is how dialogs look after opening and poking in the area with the **Search Data** checkbox:
![TotalReg_130](https://github.com/zodiacon/TotalRegistry/assets/450131/1a19595d-1ef7-4593-8de7-4f2b7bbe07d3)

If move Find window behind the borders of screen, it is cleared again.

**Comment by zodiacon** [comment]
Thanks, will look into it.

**Comment by zodiacon** [comment]
Please try the latest binary from the AllTools repo.
