### ISSUE TITLE
"Locations" -> "Explorer Context Menu" errors with "Location not found"

### ISSUE THREAD

**Issue by leumasme** [zodiacon/TotalRegistry#56]
When clicking any of the Items in the "Locations" -> "Explorer Context Menu" menu, the error "Location XX not found" where XX is the location of the entry i clicked.
![image](https://github.com/zodiacon/TotalRegistry/assets/29953391/67b30451-fae3-4944-ac8e-e0d57dba5d52)
When manually navigating there, I can see that the locations do however exist.
![image](https://github.com/zodiacon/TotalRegistry/assets/29953391/011fa36e-b401-4480-8ae7-b08d560e8bff)

**Comment by zodiacon** [comment]
Fixed, thanks!
