### ISSUE TITLE
ATL/WTL Compilation issue

### ISSUE THREAD

**Issue by NtSanya** [zodiacon/TotalRegistry#64]
So I cloned the repo but I'm having some issues getting it to compile
I'm using:

- Visual Studio 2022 (v143)
- C++ setted to std::latest but also tried with C++20

I have both SDK and WDK installed fine, I think I have all the required packages:

MFC is installed properly i think:

![MFC1](https://github.com/zodiacon/TotalRegistry/assets/102448486/25e0aa26-3ee5-43de-9809-cbe25f649dfc)

so is ATL:

![ATL](https://github.com/zodiacon/TotalRegistry/assets/102448486/de2e3090-38a9-429c-97d8-2aa7cc6b0563)

I've also installed the WTL both x32 and x64 triplets via vcpkg, but I still get an error that these files below are missing:

- atltheme.h
- atlscrl.h
- atlapp.h
- atlcrtls.h
- atlctrx.h
- atlframe.h

![image](https://github.com/zodiacon/TotalRegistry/assets/102448486/a6a2cfac-fb67-495f-8086-b507d2bb9992)

Any tips on how I can go about fixing this?

**Comment by zodiacon** [comment]
make sure you install the "static" variant of WTL: vcpkg install wtl:x64-windows-static
You can also use Nuget to get WTL instead.

**Comment by NtSanya** [comment]
I've tried that already, sadly didn't work either:

![image](https://github.com/zodiacon/TotalRegistry/assets/102448486/50aab33a-b68d-49b4-ad20-cdd38815a9cb)

**Comment by zodiacon** [comment]
MFC by the way is not needed.
Do try with Nuget - search for WTL.

**Comment by NtSanya** [comment]
Okay, very weird, doing it with Nuget seems to have worked. Not sure, maybe I was supposed to restart my machine after installing this particular package with vcpkg.

Anyways, installing the WTL with nuget got rid of those warnings, 
But then I got warnings regarding the **WIL**, had to install WIL via vcpkg, then had to disable the **SDL** (/sdl-) due to the **DwmEnableComposition** function call that was triggering **C4995** . 

It works like a charm now 

Thank you Pavel!

**Comment by zodiacon** [comment]
Thanks for the report!
