### ISSUE TITLE
Dark Mode bug in Findall window

### ISSUE THREAD

**Issue by e-t-l** [zodiacon/TotalRegistry#71]
![image](https://github.com/zodiacon/TotalRegistry/assets/40775958/f9618787-8091-4c0a-92eb-918c4b6743ed)

As you can see, the Search Options background in the Find All window doesn't become consistently dark when Dark Mode is enabled. (Also, scrollbars remain white.)

**Comment by zodiacon** [comment]
Fixed in latest commit.
Will be published in the next release.

**Comment by zodiacon** [comment]
Fixed in latest commit.
