### ISSUE TITLE
Show (Default) Value in Registry Keys

### ISSUE THREAD

**Issue by emtuls** [zodiacon/TotalRegistry#73]
I noticed that the (Default) value is not being displayed in each Key. Could it be possible to display it to keep things consistent with other Registry Tools?

**Comment by zodiacon** [comment]
It is displayed if it's not empty.

**Comment by emtuls** [comment]
Gotcha! I figured it would be nice only due to seeing it as common place in other tools, but if it's your design choice, then that's fine. 🙂
