### ISSUE TITLE
Question: Can bookmarks & user options be transferred when upgrading to the latest version of TR?

### ISSUE THREAD

**Issue by DaveF63** [zodiacon/TotalRegistry#76]
Can bookmarks & user options be transferred when upgrading to the latest version of TR?
Are they stored somewhere?

**Comment by DaveF63** [comment]
Hmm...
I'm upgrading from 9,5,0 (total-registry.exe) to the latest (TotalReg.exe)

In the registry under HKEY_CURRENT_USER\SOFTWARE\ScorpioSoftware the former saves to RegExp, the latter to TotalRegistry.

Is this expected behaviour?

![image](https://github.com/zodiacon/TotalRegistry/assets/9528328/e8eb10cf-e8ac-4fb9-8290-1d29b7786f50)

**Comment by zodiacon** [comment]
Ah, yes, you're upgrading from a relatively old version where I changed the key name to align with the tool name.
Sorry.
You can use TotalReg to copy the settings :)

**Comment by DaveF63** [comment]
I find it slightly ironic a program designed to check the registry didn't check the registry.
