### ISSUE TITLE
Feature request: show non-standard registry types

### ISSUE THREAD

**Issue by AaronMargosis** [zodiacon/TotalRegistry#82]
For example, the registry types in the subkeys of HKLM\SAM\Domains\Account\Users\Names are not standard registry types, but map to the values of the other Users subkeys.
E.g., commonly one might see ...\Users\Names\Administrator where the default value is zero length but has the type 0x1f4 -- which is the RID 500 and is associated with ...\Users\000001F4. Regedit.exe shows that non-standard type as a hex value, but TotalReg leaves the Type column empty for that value.

**Comment by zodiacon** [comment]
Thanks, Aaron. Good point. Will fix.

**Comment by zodiacon** [comment]
Done.

**Comment by AaronMargosis** [comment]
I like it. Better than regedit.exe because you're showing both decimal and hex.
